export const elementsItems =  [
    { id:1, name: 'Link', element_type: 'link', description: 'This element is used to', icon: 'fas fa-link' },
    { id:1, name: 'Heading', element_type: 'heading', description: 'This element is used to', icon: 'fas fa-heading' },
    { id:3, name: 'Avatar', element_type: 'avatar', description: 'This element is used to', icon: 'fas fa-image' },
    { id:2, name: 'Text', element_type: 'text', description: 'This element is used to', icon: 'fas fa-paragraph' },
    { id:3, name: 'Image', element_type: 'image', description: 'This element is used to', icon: 'fas fa-image' },
    // { id:4, name: 'Button', element_type: 'button', description: 'This element is used to', icon: 'fas fa-button' },
    { id:5, name: 'Video', element_type: 'video', description: 'This element is used to', icon: 'fas fa-video' },
    // { id:6, name: 'Music', element_type: 'music', description: 'This element is used to', icon: 'fas fa-audio' },
    { id:7, name: 'Social', element_type: 'social', description: 'This element is used to', icon: 'fas fa-quote-right' },
    { id:9, name: 'Quote', element_type: 'quote', description: 'This element is used to', icon: 'fas fa-quote-right' },
    { id:10, name: 'Divider', element_type: 'divider', description: 'This element is used to', icon: 'fas fa-divider' },
    // { id:11, name: 'Html', element_type: 'html', description: 'This element is used to', icon: 'fas fa-html' },
    { id:12, name: 'Location', element_type: 'location', description: 'This element is used to', icon: 'fas fa-map' },
    { id:13, name: 'Spotify', element_type: 'spotify', description: 'This element is used to', icon: 'fas fa-spotify' },
    { id:14, name: 'Mail', element_type: 'mail', description: 'This element is used to', icon: 'fas fa-mail' },
    // { id:15, name: 'Question', element_type: 'question', description: 'This element is used to', icon: 'fas fa-question' },
    { id:16, name: 'Youtube', element_type: 'youtube', description: 'This element is used to', icon: 'fas fa-youtube' },
    { id:17, name: 'Phone', element_type: 'phone', description: 'This element is used to', icon: 'fas fa-phone' },
    // { id:18, name: 'Vimeo', element_type: 'vimeo', description: 'This element is used to', icon: 'fas fa-vimeo' },
    { id:19, name: 'Soundcloud', element_type: 'soundcloud', description: 'This element is used to', icon: 'fas fa-soundcloud' },
    { id:20, name: 'Paypal', element_type: 'paypal', description: 'This element is used to', icon: 'fas fa-paypal' },
    ];
